export const PERIODS = [
  { p: 1, time: "08.30-09.25" },
  { p: 2, time: "09.25-10.20" },
  { p: 3, time: "10.20-11.15" },
  { p: 4, time: "11.15-12.10", isLunch: true },
  { p: 5, time: "12.10-13.05" },
  { p: 6, time: "13.05-14.00" },
  { p: 7, time: "14.00-14.55" },
  { p: 8, time: "14.55-15.50" },
  { p: 9, time: "15.50-16.30", isHome: true },
];

export const C = {
  sci: "#10b981",
  math: "#6366f1",
  thai: "#f59e0b",
  eng: "#3b82f6",
  soc: "#f97316",
  art: "#ec4899",
  pe: "#22c55e",
  cn: "#ef4444",
  tech: "#8b5cf6",
  act: "#64748b",
  home: "#334155",
};

export const SCHEDULE: any = {
  จันทร์: [
    {
      code: "ว22101",
      name: "วิทยาศาสตร์",
      teacher: "ครูทัศณี",
      room: "226",
      color: C.sci,
    },
    {
      code: "ว22101",
      name: "วิทยาศาสตร์",
      teacher: "ครูทัศณี",
      room: "226",
      color: C.sci,
    },
    {
      code: "ค22101",
      name: "คณิตศาสตร์",
      teacher: "ครูนิตติยา",
      room: "226",
      color: C.math,
    },
    null,
    {
      code: "อ22101",
      name: "ภาษาอังกฤษ",
      teacher: "ครูวิลาวรรณ",
      room: "226",
      color: C.eng,
    },
    {
      code: "จ20281",
      name: "ภาษาจีน",
      teacher: "ครูสุจิตรา",
      room: "226",
      color: C.cn,
    },
    {
      code: "ส22101",
      name: "สังคมศึกษา",
      teacher: "ครูวิบูลย์",
      room: "226",
      color: C.soc,
    },
    {
      code: "ส22203",
      name: "ภูมิศาสตร์",
      teacher: "ครูอำภา",
      room: "000",
      color: C.soc,
    },
    { code: "โฮมรูม", name: "โฮมรูม", teacher: "", room: "", color: C.home },
  ],
  อังคาร: [
    { code: "อบรม", name: "อบรม", teacher: "", room: "", color: C.home },
    {
      code: "ค22101",
      name: "คณิตศาสตร์",
      teacher: "ครูนิตติยา",
      room: "226",
      color: C.math,
    },
    {
      code: "ท22101",
      name: "ภาษาไทย",
      teacher: "ครูนิรัฐดิยา",
      room: "226",
      color: C.thai,
    },
    null,
    {
      code: "ว22101",
      name: "วิทยาศาสตร์",
      teacher: "ครูทัศณี",
      room: "226",
      color: C.sci,
    },
    {
      code: "ส22101",
      name: "สังคมศึกษา",
      teacher: "ครูวิบูลย์",
      room: "226",
      color: C.soc,
    },
    {
      code: "I20201",
      name: "การพิมพ์ / IS",
      teacher: "ครูพิมพ์พร",
      room: "ห้องสมุด",
      color: C.tech,
    },
    {
      code: "อ20203",
      name: "ภาษาอังกฤษเพิ่ม",
      teacher: "ครูเอื้อมพร",
      room: "226",
      color: C.eng,
    },
    { code: "โฮมรูม", name: "โฮมรูม", teacher: "", room: "", color: C.home },
  ],
  พุธ: [
    {
      code: "ส22101",
      name: "สังคมศึกษา",
      teacher: "ครูวิบูลย์",
      room: "226",
      color: C.soc,
    },
    {
      code: "ค22101",
      name: "คณิตศาสตร์",
      teacher: "ครูนิตติยา",
      room: "226",
      color: C.math,
    },
    {
      code: "ค20213",
      name: "คณิตเพิ่มเติม",
      teacher: "ครูพิรินทร",
      room: "226",
      color: C.math,
    },
    null,
    {
      code: "พ22101",
      name: "พลศึกษา",
      teacher: "ครูพลชัย",
      room: "226",
      color: C.pe,
    },
    {
      code: "อ22101",
      name: "ภาษาอังกฤษ",
      teacher: "ครูวิลาวรรณ",
      room: "226",
      color: C.eng,
    },
    {
      code: "ศ22102",
      name: "ทัศนศิลป์",
      teacher: "ครูอัชลี",
      room: "",
      color: C.art,
    },
    {
      code: "ลส/บพ",
      name: "ลูกเสือ/บำเพ็ญ",
      teacher: "ลว/นศท",
      room: "",
      color: C.pe,
    },
    { code: "โฮมรูม", name: "โฮมรูม", teacher: "", room: "", color: C.home },
  ],
  พฤหัสฯ: [
    {
      code: "พ22102",
      name: "พลศึกษา",
      teacher: "ครูพฤฒิพร",
      room: "โดม1",
      color: C.pe,
    },
    {
      code: "อ22101",
      name: "ภาษาอังกฤษ",
      teacher: "ครูวิลาวรรณ",
      room: "226",
      color: C.eng,
    },
    {
      code: "ง22103",
      name: "การงาน",
      teacher: "ครูพิมพ์พร",
      room: "ห้องสมุด",
      color: C.tech,
    },
    null,
    {
      code: "ค20213",
      name: "คณิตเพิ่มเติม",
      teacher: "ครูพิรินทร",
      room: "226",
      color: C.math,
    },
    {
      code: "ง22101",
      name: "การงาน",
      teacher: "ครูกฤษณวรรณ",
      room: "",
      color: C.tech,
    },
    {
      code: "ท22101",
      name: "ภาษาไทย",
      teacher: "ครูนิรัฐดิยา",
      room: "226",
      color: C.thai,
    },
    {
      code: "กิจกรรม",
      name: "กิจกรรมชุมนุม",
      teacher: "",
      room: "",
      color: C.act,
    },
    { code: "โฮมรูม", name: "โฮมรูม", teacher: "", room: "", color: C.home },
  ],
  ศุกร์: [
    {
      code: "ส22102",
      name: "สังคมศึกษา",
      teacher: "ครูวิบูลย์",
      room: "226",
      color: C.soc,
    },
    {
      code: "ท22101",
      name: "ภาษาไทย",
      teacher: "ครูนิรัฐดิยา",
      room: "226",
      color: C.thai,
    },
    {
      code: "ศ22101",
      name: "ดนตรีไทย",
      teacher: "ครูชลธิชา",
      room: "",
      color: C.art,
    },
    null,
    {
      code: "ก22919",
      name: "แนะแนว",
      teacher: "ครูทัศนีย์",
      room: "226",
      color: C.act,
    },
    {
      code: "I20201",
      name: "การพิมพ์ / IS",
      teacher: "ครูพิมพ์พร",
      room: "ห้องสมุด",
      color: C.tech,
    },
    {
      code: "EN20223",
      name: "ภาษาอังกฤษ",
      teacher: "ครูNew",
      room: "226",
      color: C.eng,
    },
    {
      code: "บูรณาการ",
      name: "บูรณาการ",
      teacher: "ครูนิตติยา",
      room: "226",
      color: C.math,
    },
    { code: "โฮมรูม", name: "โฮมรูม", teacher: "", room: "", color: C.home },
  ],
};

export const STUDENTS = [
  { no: 1, id: "19598", name: "เด็กชายกรวิชญ์ มาตขาว" },
  { no: 2, id: "19599", name: "เด็กชายกรวิทย์ เจียรนย" },
  { no: 3, id: "19601", name: "เด็กชายจิรายุ สาธุพันธ์" },
  { no: 4, id: "19602", name: "เด็กชายเฉลิมชัย ศรีลาเลิศ" },
  { no: 5, id: "19603", name: "เด็กชายฐีระวัฒน์ จอรนิตย์" },
  { no: 6, id: "19604", name: "เด็กชายณฐูนนท์ ธนุทอง" },
  { no: 7, id: "19607", name: "เด็กชายณัฐภิมินทร์ อ่อนสำอาง" },
  { no: 8, id: "19609", name: "เด็กชายธนโชติ พวงเงิน" },
  { no: 9, id: "19611", name: "เด็กชายปกรณ์ ดวงศรี" },
  { no: 10, id: "19678", name: "เด็กชายกนกพล รางเงิน" },
  { no: 11, id: "19696", name: "เด็กชายอภิลักษณ์ จันทหาร" },
  { no: 12, id: "19802", name: "เด็กชายณตรชัย รองสำลี" },
  { no: 13, id: "19807", name: "เด็กชายปรินทร์ ประสารแสง" },
  { no: 14, id: "19896", name: "เด็กชายศุภณัฐ มีมาก" },
  { no: 15, id: "19616", name: "เด็กหญิงกรนนก เคนพรม" },
  { no: 16, id: "19617", name: "เด็กหญิงก้านยกร สัมโย" },
  { no: 17, id: "19619", name: "เด็กหญิงขวัญข้าว พานจรุง" },
  { no: 18, id: "19622", name: "เด็กหญิงทิตะยา อนสนธิ์" },
  { no: 19, id: "19623", name: "เด็กหญิงนัชนิกาณจน์ สุดรักษา" },
  { no: 20, id: "19624", name: "เด็กหญิงณัฐณิชา วามะเกตุ" },
  { no: 21, id: "19625", name: "เด็กหญิงณัฐอิตา พิมห์พันธ์" },
  { no: 22, id: "19628", name: "เด็กหญิงนภัสร จรลี" },
  { no: 23, id: "19630", name: "เด็กหญิงน้ำฝน โขมจิตร" },
  { no: 24, id: "19631", name: "เด็กหญิงบุษรินทร์ ทองศรี" },
  { no: 25, id: "19635", name: "เด็กหญิงศุภิสรา ศรีบุตรดา" },
  { no: 26, id: "19636", name: "เด็กหญิงสดาวรรณ กุลธิ" },
  { no: 27, id: "19637", name: "เด็กหญิงอมิตา ยมพิมาย" },
  { no: 28, id: "19708", name: "เด็กหญิงธิรากรณ์ พรมสิงห์" },
  { no: 29, id: "19715", name: "เด็กหญิงวรัญญา นาจารย์" },
  { no: 30, id: "19743", name: "เด็กหญิงธัญญาภรณ์ รวมวงศ์" },
  { no: 31, id: "19749", name: "เด็กหญิงมนัสภรณ์ ภักดี" },
  { no: 32, id: "19752", name: "เด็กหญิงสิริญากรณ์ แถมวงษ์" },
  { no: 33, id: "19791", name: "เด็กหญิงลภัสรดา ศรีสว่าง" },
  { no: 34, id: "19822", name: "เด็กหญิงชฎาภา พินากัน" },
  { no: 35, id: "19825", name: "เด็กหญิงเดชินี คำสุข" },
  { no: 36, id: "19834", name: "เด็กหญิงวรนทรา โขมะจิตร" },
  { no: 37, id: "19836", name: "เด็กหญิงสุณิสา ป้องคำ" },
  { no: 38, id: "19904", name: "เด็กหญิงฐิติบัณท์ สุภาสืบ" },
  { no: 39, id: "19912", name: "เด็กหญิงพลอยใส สาธุพันธ์" },
];

export const DAYS = ["จันทร์", "อังคาร", "พุธ", "พฤหัสฯ", "ศุกร์"];

export const LEADERBOARD = [
  { id: "s5", name: "กิตติภพ ทองดี", points: 1050, rank: "Legend", streak: 14 },
  {
    id: "s2",
    name: "สุรศักดิ์ เก่งกาจ",
    points: 850,
    rank: "Master",
    streak: 21,
  },
  { id: "s6", name: "สมชาย สายเสมอ", points: 600, rank: "Elite", streak: 3 },
  { id: "s7", name: "วารุณี มีชัย", points: 420, rank: "Crystal", streak: 7 },
  { id: "s1", name: "นภัสสร เรียนดี", points: 120, rank: "Silver", streak: 5 },
  { id: "s8", name: "เอกราช ชาติไทย", points: 40, rank: "Bronze", streak: 0 },
];
